[package]
name = "csm"
version = "0.1.0"
edition = "2021"

[dependencies]
csm-macros = { path = "../csm-macros" }

[dev-dependencies]
rscx = { version = "0.1.9" }
tokio = { version = "1.13.0", features = ["full"] }
